version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget https://jcenter.bintray.com/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz
      - tar xzvf apache-maven-3.3.9-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
   pre_build:
    commands:
      - echo Entered the pre_build phase...
      - mvn -version
      - java -version
    build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - target/japi-0.1.jar
    - appspec.yml
  discard-paths: yes